# Copyright 2024 ⧉⧉⧉
#
# This file is part of helloc.
#
# helloc is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# helloc is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.
PROGRAM	= test_iseven
SRCS	= test_iseven.c		\
		 helloc.s
OBJS	= $(SRCS:%=%.o)
DEPS	= $(SRCS:%=%.d)

.DEFAULT_GOAL	:= $(PROGRAM)
.PHONY: clean test
-include $(DEPS)

$(PROGRAM): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $^ $(LDLIBS)

%.c.o: %.c
	$(CC) -MP -MMD $(CFLAGS) -o $@ -c $<

%.s.o: %.s
	$(AS) $(ASFLAGS) -o $@ $<

test: $(PROGRAM)
	@echo \--- $(PROGRAM)
	@./$(PROGRAM)

clean:
	$(RM) $(OBJS) $(DEPS)
	$(RM) $(PROGRAM)
